# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    print "Fastlane works successfully on IOS"
  end

  desc "Create app on apple developer portal and apple store connect"
  lane :creat_app do
    produce(
      username: 'hossamnasser938@gmail.com',
      app_identifier: 'com.mobile.tutorial.cicd',
      app_name: 'CICDTutorial',
      language: 'English',
      app_version: '1.0',
      sku: 'cicd_tutorial',
      team_name: 'Dicotra Tech Ltd',
    )
  end

  desc "Build IOS App"
  lane :build_locally do
    match
    gym(
      workspace: "CICDProject.xcworkspace",
      configuration: "Release",
      scheme: "CICDProject",
    )
  end
end
